### ISSUE TITLE
リソース近辺に近づいたことの判定

### ISSUE THREAD

**Issue by KenyuKurimoto** [sbgisen/rmf_resource_monitor#1]
### リソース情報の準備

リソース情報については、キーをIDとして + 座標によって管理する。
（リソースの位置や指定方法についてはRFAにて未定義なので、今回はこのようにする。）

（仮の案）
```yaml:resource_list.yaml
resources:
  - resource_id: "R01"  # リソース管理サーバーにアクセスする際に用いるID
    floor_id: "27F"
    coord_x: 0.0
    coord_y: 0.0
  - resource_id: "R02"
    floor_id: "29F"
    coord_x: 0.0
    coord_y: 0.0
```

### リソース近辺に到着判定

リソース管理サーバーにアクセスする必要があるかどうかの判定は以下のように行う。

1. スケジュールを取得（要改善）

- スケジュールを示すトピックには経路情報が含まれている
- メッセージ型は`visualization_msgs/msg/MarkerArray`、トピック名は`/schedule_markers`
- サンプルメッセージ

<details>

```
markers:
- header:
    stamp:
      sec: 1724141489
      nanosec: 41504890
    frame_id: map
  ns: participant location 0
  id: 0
  type: 3
  action: 0
  pose:
    position:
      x: 63.27253196545309
      y: -100.87733351378304
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.730536291719126
      w: 0.6828738730404526
  scale:
    x: 0.6
    y: 0.6
    z: 1.0
  color:
    r: 1.0
    g: 1.0
    b: 0.0
    a: 0.699999988079071
  lifetime:
    sec: 1
    nanosec: 0
  frame_locked: false
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 1724141489
      nanosec: 41504890
    frame_id: map
  ns: participant location 0
  id: 1
  type: 3
  action: 0
  pose:
    position:
      x: 63.27253196545309
      y: -100.87733351378304
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.730536291719126
      w: 0.6828738730404526
  scale:
    x: 1.0
    y: 1.0
    z: 0.5
  color:
    r: 0.5
    g: 1.0
    b: 0.8999999761581421
    a: 0.5
  lifetime:
    sec: 1
    nanosec: 0
  frame_locked: false
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 1724141489
      nanosec: 41504890
    frame_id: map
  ns: participant 0
  id: 0
  type: 4
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.2
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 1.0
    b: 0.0
    a: 0.699999988079071
  lifetime:
    sec: 1
    nanosec: 0
  frame_locked: false
  points:
  - x: 63.27253196545309
    y: -100.87733351378304
    z: 0.1
  - x: 62.71410235166881
    y: -92.60674447076666
    z: 0.1
  - x: 62.71006035884656
    y: -92.54688077313591
    z: 0.1
  - x: 62.71006035884656
    y: -92.54688077313591
    z: 0.1
  - x: 62.71006035884656
    y: -92.54688077313591
    z: 0.1
  - x: 62.71006035884656
    y: -92.54688077313591
    z: 0.1
  - x: 62.65006569227406
    y: -92.54768076241992
    z: 0.1
  - x: 48.34233790594017
    y: -92.73846486976458
    z: 0.1
  - x: 48.28234323936766
    y: -92.73926485904859
    z: 0.1
  - x: 48.28234323936766
    y: -92.73926485904859
    z: 0.1
  - x: 48.28234323936766
    y: -92.73926485904859
    z: 0.1
  - x: 48.28234323936766
    y: -92.73926485904859
    z: 0.1
  - x: 48.27410494940181
    y: -92.79869658944943
    z: 0.1
  - x: 47.44460305996562
    y: -98.78279436511666
    z: 0.1
  - x: 47.43636476999977
    y: -98.8422260955175
    z: 0.1
  - x: 47.43636476999977
    y: -98.8422260955175
    z: 0.1
  - x: 47.43636476999977
    y: -98.8422260955175
    z: 0.1
  - x: 47.43636476999977
    y: -98.8422260955175
    z: 0.1
  - x: 47.37667440664513
    y: -98.83613836009366
    z: 0.1
  - x: 43.64723672921646
    y: -98.45577830557346
    z: 0.1
  - x: 43.58754636586182
    y: -98.44969057014961
    z: 0.1
  - x: 43.58754636586182
    y: -98.44969057014961
    z: 0.1
  - x: 43.58754636586182
    y: -98.44969057014961
    z: 0.1
  - x: 43.58754636586182
    y: -98.44969057014961
    z: 0.1
  - x: 43.58754636586182
    y: -98.44969057014961
    z: 0.1
  - x: 43.58825226475207
    y: -98.50968641756222
    z: 0.1
  - x: 43.59887039258009
    y: -99.4121436756378
    z: 0.1
  - x: 43.59957629147034
    y: -99.4721395230504
    z: 0.1
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
```
</details>

2. 特定近傍距離以内にロボットが移動したことの判定

- あるロボットの現在位置についてはフリートのステータスを示すトピックから取得する
- メッセージ型は`rmf_fleet_msgs/msg/FleetState`、トピック名は`/fleet_states`
- サンプルメッセージ
- 
<details>

```
name: cuboid
robots:
- name: cuboid0001
  model: cuboid
  task_id: ''
  seq: 0
  mode:
    mode: 0
    mode_request_id: 0
    performing_action: ''
  battery_percent: 0.0
  location:
    t:
      sec: 1724142292
      nanosec: 897695789
    x: 63.32915496826172
    y: -101.71595764160156
    yaw: -2.930743932723999
    obey_approach_speed_limit: false
    approach_speed_limit: 0.0
    level_name: 27F
    index: 0
  path: []
```

</details>
